### ISSUE TITLE
Database structure

### ISSUE THREAD

**Issue by Hekotoru** [davidtavarez/fiao#12]
We have to define the table structure to acomplish our requeriments. This is an idea of how should be define:

# Products

|   Name      | Type           
| ------------- |:-------------:
| Id    |   numeric
| Name      | varchar 
| Description     | varchar    
| Quantity | numeric    
| Price | numeric 

# Users

|   Name      | Type           
| ------------- |:-------------:
| Id    |   numeric
| Name      | varchar 
| Last Name     | varchar    
| Type | numeric    
| Debt ID  | numeric

# Debts

|   Name      | Type           
| ------------- |:-------------:
| Id      | varchar 
| Quantity     | varchar

**Comment by GianCastle** [comment]
**Products**
- I think we don't need the description of the products, because the product that we could buy aren't so complex for being described on the application. It's also tedious for the salesman to have to put a detail of each one of the products (IKR, this could be a non-required 

**Users**
- How about removing Name and Last Name and just put a field that calls FullName?

**Debts**
- Quantity should be numeric.

**Pros**
- We should have a Category table.

**Comment by davidtavarez** [comment]
We need to keep the price separated from the product. We need something like this.

# Sale

|   Name      | Type           
| ------------- |:-------------:
| product_id    |   numeric
| user_id      | numeric 
| quantity     | numeric    
| price | numeric    
| time | datetime 

Also, we should save the admin password.

# Settings
|   Name      | Type           
| ------------- |:-------------:
| password    |   varchar

**Comment by Hekotoru** [comment]
In resume we have the following structure:

# Products

|   Name      | Type           
| ------------- |:-------------:
| Id    |   numeric
| Name      | varchar 

# Users

|   Name      | Type           
| ------------- |:-------------:
| Id    |   numeric
| FullName      | varchar 
| Type | numeric    
| Debt ID  | numeric

# Debts

|   Name      | Type           
| ------------- |:-------------:
| Id      | varchar 
| Quantity     | numeric    

# Sale

|   Name      | Type           
| ------------- |:-------------:
| product_id    |   numeric
| user_id      | numeric 
| quantity     | numeric    
| price | numeric    
| time | datetime 


# Settings
|   Name      | Type           
| ------------- |:-------------:
| password    |   varchar

# UserType

|   Name      | Type           
| ------------- |:-------------:
| Id    |   numeric
| Description      | varchar 

Let me know if everyone is okey with this structure to start making the seeders and migrations
